donnees<-read.csv("http://afalco.hol.es/cursos/nutriage.csv",header=TRUE)
View(donnees)
attach(donnees)
length(taille)
plot(poids,taille,col='blue')
cov(poids,taille) 
cor(poids,taille)
acos(cor(poids,taille))
help("acos")
acos(cor(poids,taille))*180/pi
lm(poids~taille)
lm(taille~poids)
taille.example<-taille
poids.example<-poids
length(taille.example)
taille.example[227]<-400
poids.example[227]<-300
plot(poids.example,taille.example,col='red')
cov(poids.example,taille.example)
cor(poids.example,taille.example)
max(poids)
max(poids.example)
min(poids.example)
median(poids.example)
boxplot(poids.example)
